### PR TITLE
Move some devDependencies to dependencies

### PR DESCRIPTION
**Pull request by tiemevanveen**
I admit, not having `react`, or `react-dom` installed when using skin deep is a weird scenario... But I did not used the `react-addons-test-utils` before and my tested failed after adding and using skin deep: `Error: Cannot find module 'react-addons-test-utils'`.

It's quite handy that you abstract the boilerplate away but I think you should then also list it as a dependency so users don't need to install it manually right? 

Thanks anyway, works like a charm!

### CODE REVIEW

**Comment by glenjamin** [comment]
Unfortunately, this is a bit trickier - the current version of this lib works on React 0.13 and 0.14 - and those modules don't exist on 0.13.

We'd also need to share those libraries with the rest of your application, so they' need to be peer dependencies anway.

I'll see about adding something to the docs about this.

**Comment by tiemevanveen** [comment]
Check, that makes sense.

**Comment by glenjamin** [comment]
Closed via ccf4b46
